kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-project-editor
rules:
  - verbs:
      - get
      - list
      - watch
      - patch
    apiGroups:
      - ''
    resources:
      - namespaces
  - verbs:
      - get
      - list
      - watch
      - create
      - patch
    apiGroups:
      - 'project.openshift.io'
    resources:
      - projects
  - verbs:
      - get
      - list
      - watch
      - create
      - patch
    apiGroups:
      - ''
    resources:
      - resourcequotas